### YamlMime:ModuleUnit
uid: learn.pillars-of-a-great-azure-architecture.3-design-for-security
title: Design för säkerhet
metadata:
  title: Design för säkerhet
  description: Design för säkerhet
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 2de603cd1ad3f12b84e27c922d0f04aab19fce07
  ms.sourcegitcommit: b7b4489eb7352bcc722ed6c2ff27b70dd212e9c5
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/14/2018
  ms.locfileid: "45621842"
durationInMinutes: 10
content: >
  [!include[](includes/3-design-for-security.md)]
quiz:
  title: Kunskapskontroll – Design för säkerhet
  questions:
  - content: Vilka av följande typer av data kan behöva ha säkerhetsskydd?
    choices:
    - content: Kundinformation som innehåller personuppgifter
      isCorrect: false
      incorrectExplanation: Det är viktigt att ge dessa data rätt säkerhetsskydd men det är inte det enda rätta valet.
    - content: Finansiella data som stöd för verksamheten
      isCorrect: false
      incorrectExplanation: Det är viktigt att ge dessa data rätt säkerhetsskydd men det är inte det enda rätta valet.
    - content: Immateriella rättigheter
      isCorrect: false
      incorrectExplanation: Det är viktigt att ge dessa data rätt säkerhetsskydd men det är inte det enda rätta valet.
    - content: Alla alternativ ovan kan behöva säkerhetsskydd
      isCorrect: true
      correctExplanation: Alla alternativ ovan kan ha ytterligare säkerhetsskydd.
  - content: Vilket av följande är ett exempel på en attack du kan se på princip- och åtkomstnivå?
    choices:
    - content: Exponerade autentiseringsuppgifter som publicerats online
      isCorrect: true
      correctExplanation: Exponerade autentiseringsuppgifter är en enorm risk för en organisation och gäller på princip- och åtkomstnivå.
    - content: En SYN flood-attack
      isCorrect: false
      incorrectExplanation: SYN flood-attacker är en typ av DoS-attack som ofta sker i nätverksperimetern.
    - content: Följa efter en anställd in i ett datacenter utan at behöva ange autentiseringsuppgifter
      isCorrect: false
      incorrectExplanation: Att följa efter en anställd in i ett datacenter är ett angrepp på fysisk nivå.
    - content: Utpressningstrojaner som krypterar diskarna för en virtuell dator
      isCorrect: false
      incorrectExplanation: Utpressningstrojaner är en attack på VM-/beräkningsnivå.
