### YamlMime:ModuleUnit
uid: learn.create-azure-storage-account.3-choose-your-account-settings
title: <span data-ttu-id="7443d-101">Välj kontoinställningar</span><span class="sxs-lookup"><span data-stu-id="7443d-101">Choose your account settings</span></span>
metadata:
  title: <span data-ttu-id="7443d-102">Välj kontoinställningar</span><span class="sxs-lookup"><span data-stu-id="7443d-102">Choose your account settings</span></span>
  description: <span data-ttu-id="7443d-103">Välj kontoinställningar</span><span class="sxs-lookup"><span data-stu-id="7443d-103">Choose your account settings</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 86463780f25a2aa164342d6539d35ec5586984af
  ms.sourcegitcommit: b6f5aa15bae13cb0f53667fba1d404b7bec76f67
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/17/2018
  ms.locfileid: "45754002"
durationInMinutes: 5
content: '[!include[](includes/3-choose-your-account-settings.md)]'
