### YamlMime:ModuleUnit
uid: learn.enable-reliable-messaging-for-big-data-applications-using-azure-event-hubs.4-configure-applications-to-send-or-receive-messages-through-an-event-hub
title: Konfigurera appar för att skicka eller ta emot meddelanden via en händelsehubb
metadata:
  title: Konfigurera appar för att skicka eller ta emot meddelanden via en händelsehubb
  description: Konfigurera appar för att skicka eller ta emot meddelanden via en händelsehubb
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 94af9097bf2ee37e91e93d2e51d1d5cc79eb874d
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44230729"
durationInMinutes: 5
content: '[!include[](includes/4-configure-applications-to-send-or-receive-messages-through-an-event-hub.md)]'
