### YamlMime:ModuleUnit
uid: learn.caching-and-performance-azure-storage-and-disks.6-exercise-manage-cache-settings-with-powershell
title: Övning – Hantera cacheinställningar med PowerShell
metadata:
  title: Övning – Hantera cacheinställningar med PowerShell
  description: Övning – Hantera cacheinställningar med PowerShell
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 7bb787e2ea32d2ccc5a912c10d2a7c348b656633
  ms.sourcegitcommit: b21a4b22de591cfa776684ba2eab9ba27248c65d
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/19/2018
  ms.locfileid: "46355319"
interactive: powershell
azureSandbox: true
durationInMinutes: 10
content: '[!include[](includes/6-exercise-manage-cache-settings-with-powershell.md)]'
