### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.1-create-azure-iot-central-application
title: <span data-ttu-id="f7ddb-101">Skapa ett Azure IoT Central-program</span><span class="sxs-lookup"><span data-stu-id="f7ddb-101">Create an Azure IoT Central application</span></span>
metadata:
  title: <span data-ttu-id="f7ddb-102">Skapa ett Azure IoT Central-program</span><span class="sxs-lookup"><span data-stu-id="f7ddb-102">Create an Azure IoT Central application</span></span>
  description: <span data-ttu-id="f7ddb-103">Skapa ett Azure IoT Central-program</span><span class="sxs-lookup"><span data-stu-id="f7ddb-103">Create an Azure IoT Central application</span></span>
  ms.openlocfilehash: e8c698bdbf44cc17d687466702c06b59f7023806
  ms.sourcegitcommit: b97ed72bd7e3fb77b49de71e8ef35d3f70dfd636
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/05/2018
  ms.locfileid: "43796395"
durationInMinutes: 12
content: '[!include[](includes/1-create-azure-iot-central-application.md)]'
