### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.5-configure-rules-and-actions
title: Konfigurera regler och åtgärder för att övervaka din kaffebryggare
metadata:
  title: Konfigurera regler och åtgärder för att övervaka din kaffebryggare
  description: Konfigurera regler och åtgärder för att övervaka din kaffebryggare
  ms.openlocfilehash: b88da62e3fbf019371ec59a009d2a52e3ced1b75
  ms.sourcegitcommit: b97ed72bd7e3fb77b49de71e8ef35d3f70dfd636
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/05/2018
  ms.locfileid: "43796430"
durationInMinutes: 12
content: '[!include[](includes/5-configure-rules-and-actions.md)]'
