### YamlMime:ModuleUnit
uid: learn.connect-app-to-azure-storage.10-exercise-connect-with-your-azure-storage-configuration
title: <span data-ttu-id="8f9e2-101">Anslut till din Azure Storage-konfiguration</span><span class="sxs-lookup"><span data-stu-id="8f9e2-101">Connect with your Azure Storage configuration</span></span>
metadata:
  title: <span data-ttu-id="8f9e2-102">Anslut till din Azure Storage-konfiguration</span><span class="sxs-lookup"><span data-stu-id="8f9e2-102">Connect with your Azure Storage configuration</span></span>
  description: <span data-ttu-id="8f9e2-103">Anslut till din Azure Storage-konfiguration</span><span class="sxs-lookup"><span data-stu-id="8f9e2-103">Connect with your Azure Storage configuration</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  zone_pivot_groups: dev-lang-csharp-javascript
  ms.openlocfilehash: 744fed3cd3989012c289c6255818479a6f1f7d2b
  ms.sourcegitcommit: b6f5aa15bae13cb0f53667fba1d404b7bec76f67
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/17/2018
  ms.locfileid: "45760921"
interactive: bash-editor
azureSandbox: true
durationInMinutes: 15
content: '[!include[](includes/10-exercise-connect-with-your-azure-storage-configuration.md)]'
