### YamlMime:ModuleUnit
uid: learn.connect-app-to-azure-storage.8-exercise-add-azure-storage-configuration-to-your-app
title: <span data-ttu-id="7b87b-101">Lägga till Azure Storage-konfiguration i din app</span><span class="sxs-lookup"><span data-stu-id="7b87b-101">Add Azure Storage configuration to your app</span></span>
metadata:
  title: <span data-ttu-id="7b87b-102">Lägga till Azure Storage-konfiguration i din app</span><span class="sxs-lookup"><span data-stu-id="7b87b-102">Add Azure Storage configuration to your app</span></span>
  description: <span data-ttu-id="7b87b-103">Lägga till Azure Storage-konfiguration i din app</span><span class="sxs-lookup"><span data-stu-id="7b87b-103">Add Azure Storage configuration to your app</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  zone_pivot_groups: dev-lang-csharp-javascript
  ms.openlocfilehash: 9ed11b520e16ccaf47e786ff5a63272921f4bf90
  ms.sourcegitcommit: b6f5aa15bae13cb0f53667fba1d404b7bec76f67
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/17/2018
  ms.locfileid: "45756076"
interactive: bash-editor
azureSandbox: true
durationInMinutes: 10
content: '[!include[](includes/8-exercise-add-azure-storage-configuration-to-your-app.md)]'
