### YamlMime:ModuleUnit
uid: learn.manage-secrets-with-azure-key-vault.6-configure-deploy-run-azure
title: <span data-ttu-id="e4516-101">Konfigurera, distribuera och köra i Azure</span><span class="sxs-lookup"><span data-stu-id="e4516-101">Configure, deploy, and run in Azure</span></span>
metadata:
  title: <span data-ttu-id="e4516-102">Konfigurera, distribuera och köra i Azure</span><span class="sxs-lookup"><span data-stu-id="e4516-102">Configure, deploy, and run in Azure</span></span>
  description: <span data-ttu-id="e4516-103">Konfigurera, distribuera och köra i Azure</span><span class="sxs-lookup"><span data-stu-id="e4516-103">Configure, deploy, and run in Azure</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: c821587b542dde7521edab678b43097232763181
  ms.sourcegitcommit: 8213d1af6ad9da967a5e195f0b40b00265cb192c
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/10/2018
  ms.locfileid: "44310127"
durationInMinutes: 12
interactive: bash
azureSandbox: true
content: '[!include[](includes/6-configure-deploy-run-azure.md)]'
