### YamlMime:ModuleUnit
uid: learn.intro-to-containers.2-configure-local
metadata:
  title: <span data-ttu-id="67620-101">Konfigurera en lokal miljö för containerutveckling</span><span class="sxs-lookup"><span data-stu-id="67620-101">Configure a local container development environment</span></span>
  description: <span data-ttu-id="67620-102">Konfigurera en lokal miljö för containerutveckling.</span><span class="sxs-lookup"><span data-stu-id="67620-102">Configure a local container development environment.</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 365b86322b9585abcedd1a61fdcf91840bae48bf
  ms.sourcegitcommit: b6f5aa15bae13cb0f53667fba1d404b7bec76f67
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/17/2018
  ms.locfileid: "45758637"
title: <span data-ttu-id="67620-103">Konfigurera en lokal miljö för containerutveckling</span><span class="sxs-lookup"><span data-stu-id="67620-103">Configure a local container development environment</span></span>
durationInMinutes: 10
content: '[!include[](includes/2-configure-local.md)]'
