### YamlMime:ModuleUnit
uid: learn.host-a-web-application-with-azure-web-apps.4-create-an-asp.net-core-web-application-on-linux-content
title: Använda ASP.NET Core på Linux
metadata:
  title: Använda ASP.NET Core på Linux
  description: Använda ASP.NET Core på Linux
  ms.openlocfilehash: 2fcb099e0fd2344e4fd871da8dcc7acadf3dbfca
  ms.sourcegitcommit: b1b68b477ab39109c48f227b504a5050cae7a718
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/01/2018
  ms.locfileid: "43411399"
durationInMinutes: 10
content: '[!include[](includes/4-create-an-asp.net-core-web-application-on-linux-content.md)]'
