### YamlMime:ModuleUnit
uid: learn.optimize-web-app-with-redis.3-configure-redis-cache
title: <span data-ttu-id="9bc26-101">Konfigurera Redis Cache</span><span class="sxs-lookup"><span data-stu-id="9bc26-101">Configure Redis cache</span></span>
metadata:
  title: <span data-ttu-id="9bc26-102">Konfigurera Redis Cache</span><span class="sxs-lookup"><span data-stu-id="9bc26-102">Configure Redis cache</span></span>
  description: <span data-ttu-id="9bc26-103">Konfigurera Redis Cache</span><span class="sxs-lookup"><span data-stu-id="9bc26-103">Configure Redis cache</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: cf34eb91055b1a3f200c204af82bc93cb86e156f
  ms.sourcegitcommit: b21a4b22de591cfa776684ba2eab9ba27248c65d
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/19/2018
  ms.locfileid: "46359999"
durationInMinutes: 5
content: '[!include[](includes/3-configure-redis-cache.md)]'
