### YamlMime:ModuleUnit
uid: learn.optimize-web-app-with-redis.3-configure-redis-cache
title: Konfigurera Redis Cache
metadata:
  title: Konfigurera Redis Cache
  description: Konfigurera Redis Cache
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 5
content: |
  [!include[](includes/3-configure-redis-cache.md)]