### YamlMime:ModuleUnit
uid: learn.run-docker-containers-aci.4-use-environment-variables
metadata:
  title: <span data-ttu-id="800e3-101">Ange miljövariabler</span><span class="sxs-lookup"><span data-stu-id="800e3-101">Set environment variables</span></span>
  description: <span data-ttu-id="800e3-102">Ange miljövariabler i Azure Container Instances.</span><span class="sxs-lookup"><span data-stu-id="800e3-102">Set environment variables in Azure Container Instances.</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 121d22c224c33875cf10038d9c63596882a3b1f4
  ms.sourcegitcommit: b6f5aa15bae13cb0f53667fba1d404b7bec76f67
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/17/2018
  ms.locfileid: "45760751"
title: <span data-ttu-id="800e3-103">Ange miljövariabler</span><span class="sxs-lookup"><span data-stu-id="800e3-103">Set environment variables</span></span>
interactive: bash
azureSandbox: true
durationInMinutes: 10
content: '[!include[](includes/4-use-environment-variables.md)]'
