### YamlMime:ModuleUnit
uid: learn.store-app-data-with-azure-blob-storage.5-configure-and-initialize-the-client-library
title: <span data-ttu-id="79a34-101">Konfigurera och initiera klientbiblioteket</span><span class="sxs-lookup"><span data-stu-id="79a34-101">Configure and initialize the client library</span></span>
metadata:
  title: <span data-ttu-id="79a34-102">Konfigurera och initiera klientbiblioteket</span><span class="sxs-lookup"><span data-stu-id="79a34-102">Configure and initialize the client library</span></span>
  description: <span data-ttu-id="79a34-103">Konfigurera och initiera klientbiblioteket</span><span class="sxs-lookup"><span data-stu-id="79a34-103">Configure and initialize the client library</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: bedd297c48ead2c2aadba57e57e3bb8b965344fb
  ms.sourcegitcommit: 8213d1af6ad9da967a5e195f0b40b00265cb192c
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/10/2018
  ms.locfileid: "44307527"
durationInMinutes: 10
interactive: bash-editor
azureSandbox: true
content: '[!include[](includes/5-configure-and-initialize-the-client-library.md)]'
