### YamlMime:ModuleUnit
uid: learn.store-app-data-with-azure-blob-storage.5-configure-and-initialize-the-client-library
title: <span data-ttu-id="048c5-101">Konfigurera och initiera klientbiblioteket</span><span class="sxs-lookup"><span data-stu-id="048c5-101">Configure and initialize the client library</span></span>
metadata:
  title: <span data-ttu-id="048c5-102">Konfigurera och initiera klientbiblioteket</span><span class="sxs-lookup"><span data-stu-id="048c5-102">Configure and initialize the client library</span></span>
  description: <span data-ttu-id="048c5-103">Konfigurera och initiera klientbiblioteket</span><span class="sxs-lookup"><span data-stu-id="048c5-103">Configure and initialize the client library</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 8744fec530af1a6a8ff4d555b7945c37aa4338d6
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44231817"
durationInMinutes: 10
interactive: bash-editor
content: '[!include[](includes/5-configure-and-initialize-the-client-library.md)]'
