### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.1-create-azure-iot-central-application
title: <span data-ttu-id="a3a86-101">Skapa ett Azure IoT Central-program</span><span class="sxs-lookup"><span data-stu-id="a3a86-101">Create an Azure IoT Central application</span></span>
metadata:
  title: <span data-ttu-id="a3a86-102">Skapa ett Azure IoT Central-program</span><span class="sxs-lookup"><span data-stu-id="a3a86-102">Create an Azure IoT Central application</span></span>
  description: <span data-ttu-id="a3a86-103">Skapa ett Azure IoT Central-program</span><span class="sxs-lookup"><span data-stu-id="a3a86-103">Create an Azure IoT Central application</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 98e9a83d594bc3611f3048909b7d238ea289901e
  ms.sourcegitcommit: b6f5aa15bae13cb0f53667fba1d404b7bec76f67
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/17/2018
  ms.locfileid: "45774555"
durationInMinutes: 5
content: '[!include[](includes/1-create-azure-iot-central-application.md)]'
