### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.3-connect-your-application-to-simulator
title: <span data-ttu-id="2775b-101">Ansluta din simulerade kaffebryggare till programmet</span><span class="sxs-lookup"><span data-stu-id="2775b-101">Connect your simulated coffee machine to the application</span></span>
metadata:
  title: <span data-ttu-id="2775b-102">Ansluta din simulerade kaffebryggare till programmet</span><span class="sxs-lookup"><span data-stu-id="2775b-102">Connect your simulated coffee machine to the application</span></span>
  description: <span data-ttu-id="2775b-103">Ansluta din simulerade kaffebryggare till programmet</span><span class="sxs-lookup"><span data-stu-id="2775b-103">Connect your simulated coffee machine to the application</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 5e1c175df222a53ef2cd352fbd12feceabe25fad
  ms.sourcegitcommit: 46c8d35790efaafa6a4637f7688482e3a754d7f3
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44256647"
durationInMinutes: 5
content: '[!include[](includes/3-connect-your-application-to-simulator.md)]'
