### YamlMime:ModuleUnit
uid: learn.host-a-web-application-with-azure-app-service.5-exercise-create-an-asp.net-core-web-application-on-linux
title: <span data-ttu-id="fd3a3-101">Övning – Skapa ett ASP.NET Core-program på Linux</span><span class="sxs-lookup"><span data-stu-id="fd3a3-101">Exercise - Create an ASP.NET Core application on Linux</span></span>
metadata:
  title: <span data-ttu-id="fd3a3-102">Övning – Skapa ett ASP.NET Core-program på Linux</span><span class="sxs-lookup"><span data-stu-id="fd3a3-102">Exercise - Create an ASP.NET Core application on Linux</span></span>
  description: <span data-ttu-id="fd3a3-103">Övning – Skapa ett ASP.NET Core-program på Linux</span><span class="sxs-lookup"><span data-stu-id="fd3a3-103">Exercise - Create an ASP.NET Core application on Linux</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 539e279d78694c171f88ff3c73563acdf77ca192
  ms.sourcegitcommit: 7de323416e472639edcff135bfc7d47bd5715256
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/11/2018
  ms.locfileid: "44372990"
durationInMinutes: 10
content: '[!include[](includes/5-exercise-create-an-asp.net-core-web-application-on-linux.md)]'
